name: deployment-test

on:
  deployment:
  workflow_dispatch:
env:
  DEPLOY: ${{ github.event_name == 'workflow_dispatch' }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Deploy
        if: env.DEPLOY
        run: echo "Deploy"
