name: deployment-test

on:
  deployment:
  workflow_dispatch:
env:
  DEPLOY: ${{ (github.event_name == 'deployment') || (github.event_name == 'workflow_dispatch') }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TESTING: 'true'
    if: env.DEPLOY == 'true'
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump Env
        env:
          ALL_ENV: ${{ toJSON(env) }}
        run: echo "$ALL_ENV"
        
      - name: Deploy
        if: env.DEPLOY == 'true'
        run: echo "Deploy"
